---
- hosts: all
- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- hosts: include env-vars file
- import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import database file
- import_playbook: ../static-assignments/db.yml

- name: import webservers file
- import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  tasks:
    - name: Include load balancers playbook
      include_tasks: ../static-assignments/loadbalancers.yml

